# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_celery', '0002_adhoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('hosts', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=128)),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ansible_beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('hosts', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=128)),
                ('interval', models.CharField(max_length=128)),
                ('crond', models.CharField(max_length=128)),
                ('log_date', models.DateTimeField()),
            ],
        ),
    ]
