# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_celery', '0003_ansible_ansible_beat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ansible_beat',
        ),
    ]
